### ISSUE TITLE
Link to RSS feed is broken

### ISSUE THREAD

**Issue by mcmxcdev** [mickeygousset/mickeygousset#1]
When clicking the RSS button on your website, it leads to a messed up URL like: https://http//mickeygousset.com/feed.xml

![2020-08-26_10-57](https://user-images.githubusercontent.com/16797721/91283564-0a72fd80-e78b-11ea-8f74-ae86cfbb570b.png)

Apart from that, I can recommend upgrading your website to be delivered in https ;)

**Comment by mickeygousset** [comment]
@mhatvan Thank you for letting me know about the above link. I'll get it fixed.

Adding a cert is on the backlog. Thank you for bumping it up my list.

**Comment by mickeygousset** [comment]
Fixed!  Fixed the RSS link and the HTTPS issue. Thank you again @mhatvan!

**Comment by mcmxcdev** [comment]
Yes, just verified that it works as expected and https is active, good job!
